In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn


In [4]:
path = "https://github.com/flaurensia05/TugasML/blob/main/Q3_competition_detail_dataset.xlsx?raw=true"
dataset = pd.read_excel (path)
dataset

id  ... cross_streets
0      nzgC5hhlnSq2DYbJbtH5MQ  ...           NaN
1      i-2aG9_PQBEy7LrsRv0Ivg  ...           NaN
2      DJoeogRsOW5s9MzgveHQ2A  ...           NaN
3      hwWfv3sSxV3a47UAdSVT5w  ...           NaN
4      TxU0fwF2N2nVhCpzokc1Pg  ...           NaN
...                       ...  ...           ...
10705  7mOOAeGIh2QL3GBCbAspYA  ...           NaN
10706  Qd8G5bJaOQp17q33q-5rjg  ...           NaN
10707  tNQjsxKstD0pHs-iVjnsrw  ...           NaN
10708  A1k_7CpM0cFoEN2I-6gC2A  ...           NaN
10709  R3LoXVj1nnc7FE7klhJdLA  ...           NaN

[10710 rows x 21 columns]

In [5]:
dataset

id  ... cross_streets
0      nzgC5hhlnSq2DYbJbtH5MQ  ...           NaN
1      i-2aG9_PQBEy7LrsRv0Ivg  ...           NaN
2      DJoeogRsOW5s9MzgveHQ2A  ...           NaN
3      hwWfv3sSxV3a47UAdSVT5w  ...           NaN
4      TxU0fwF2N2nVhCpzokc1Pg  ...           NaN
...                       ...  ...           ...
10705  7mOOAeGIh2QL3GBCbAspYA  ...           NaN
10706  Qd8G5bJaOQp17q33q-5rjg  ...           NaN
10707  tNQjsxKstD0pHs-iVjnsrw  ...           NaN
10708  A1k_7CpM0cFoEN2I-6gC2A  ...           NaN
10709  R3LoXVj1nnc7FE7klhJdLA  ...           NaN

[10710 rows x 21 columns]

In [135]:
data = pd.read_excel ('Feature_and_independent.xlsx')
data

id                          name  ...  rating  is_claimed
0      nzgC5hhlnSq2DYbJbtH5MQ   Foxy's Landing & Restaurant  ...     4.0        True
1      i-2aG9_PQBEy7LrsRv0Ivg           Mosman's Steakhouse  ...     3.5        True
2      DJoeogRsOW5s9MzgveHQ2A                  El Tamarindo  ...     3.5        True
3      hwWfv3sSxV3a47UAdSVT5w                        Subway  ...     2.5        True
4      TxU0fwF2N2nVhCpzokc1Pg                Little Caesars  ...     1.5        True
...                       ...                           ...  ...     ...         ...
10705  7mOOAeGIh2QL3GBCbAspYA        San Antonio Restaurant  ...     4.0        True
10706  Qd8G5bJaOQp17q33q-5rjg                Prontos Market  ...     3.5       False
10707  tNQjsxKstD0pHs-iVjnsrw                 El Pollo Loco  ...     1.5        True
10708  A1k_7CpM0cFoEN2I-6gC2A  La Perla Tapatia Meat Market  ...     4.5        True
10709  R3LoXVj1nnc7FE7klhJdLA          Tacos Tamix Truck #1  ...     3.5       False

[10710 rows x 5 columns]

In [136]:
from sklearn.preprocessing import LabelEncoder

In [137]:
enc = LabelEncoder()

In [138]:
data ['id'] = enc.fit_transform(data['id'].values)
data ['name'] = enc.fit_transform(data['name'].values)
data ['is_claimed'] = enc.fit_transform(data['is_claimed'].values)


In [139]:
data

id  name  review_count  rating  is_claimed
0      8696  2384            52     4.0           1
1      7645  4634            63     3.5           1
2      2250  2151            11     3.5           1
3      7635  6375            13     2.5           1
4      5030  3910            54     1.5           1
...     ...   ...           ...     ...         ...
10705  1391  5956            12     4.0           1
10706  4473  5528             3     3.5           0
10707  9606  2099           165     1.5           1
10708  1725  3713            81     4.5           1
10709  4538  6747             3     3.5           0

[10710 rows x 5 columns]

In [141]:
X = data.iloc[:,:4].values
Y = data.iloc[:, 4].values

In [142]:
print (X)

[[8.696e+03 2.384e+03 5.200e+01 4.000e+00]
 [7.645e+03 4.634e+03 6.300e+01 3.500e+00]
 [2.250e+03 2.151e+03 1.100e+01 3.500e+00]
 ...
 [9.606e+03 2.099e+03 1.650e+02 1.500e+00]
 [1.725e+03 3.713e+03 8.100e+01 4.500e+00]
 [4.538e+03 6.747e+03 3.000e+00 3.500e+00]]


In [143]:
print (Y)

[1 1 1 ... 1 1 0]


Split Data

In [144]:
from sklearn.model_selection import train_test_split

In [145]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [146]:
print (X_train)

[[9.4150e+03 6.4160e+03 1.0000e+00 1.0000e+00]
 [1.4890e+03 1.8000e+03 1.3700e+02 2.0000e+00]
 [3.7000e+01 5.9700e+02 7.1000e+01 4.5000e+00]
 ...
 [1.8030e+03 4.1900e+03 1.7900e+02 4.0000e+00]
 [3.4940e+03 5.3670e+03 5.1000e+01 3.0000e+00]
 [1.0178e+04 5.2100e+03 2.6300e+02 4.5000e+00]]


In [147]:
print (X_test)

[[1.320e+03 3.006e+03 6.785e+03 4.500e+00]
 [6.939e+03 3.520e+03 2.860e+02 4.500e+00]
 [8.516e+03 3.154e+03 3.600e+01 2.500e+00]
 ...
 [8.429e+03 1.312e+03 6.200e+01 3.000e+00]
 [5.248e+03 3.999e+03 3.100e+01 4.000e+00]
 [6.340e+03 6.989e+03 8.400e+01 4.500e+00]]


Feature Scaling

In [148]:
from sklearn.preprocessing import StandardScaler

In [158]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)


In [150]:
print (X_train)

[[ 1.31671247  1.00112066 -0.49519056 -2.88914442]
 [-1.24885167 -0.98936204 -0.25323223 -1.78025964]
 [-1.71884903 -1.50811219 -0.37065319  0.99195231]
 ...
 [-1.14721312  0.04123884 -0.1785098   0.43750992]
 [-0.59985392  0.54877743 -0.40623529 -0.67137486]
 [ 1.56368767  0.48107687 -0.02906495  0.99195231]]


Training

In [170]:
from sklearn.naive_bayes import GaussianNB


In [164]:
tree_data = GaussianNB()


In [165]:
tree_data.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

Predict Result

In [167]:
Y_pred = tree_data.predict (X_test)

In [168]:
print (Y_pred)

[1 1 0 ... 1 1 1]


In [169]:
print (Y_test)

[1 1 1 ... 1 0 1]


Evaluasi

In [171]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [172]:
cm = confusion_matrix(Y_test, Y_pred)
ac = accuracy_score (Y_test, Y_pred)

Nilai Akurasi score

In [173]:
ac

0.7628384687208216